# Wrangler Configuration for Cloudflare Pages

name = "tarott"
compatibility_date = "2023-10-30"

# Specify the build output directory for React
[build]
command = "npm run build"

[site]
bucket = "./build"

# This tells Cloudflare Pages where to find the build output
[build.upload]
format = "directory"
pages_build_output_dir = "build"
